AWSTemplateFormatVersion: '2010-09-09'
Resources:
  book:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: book
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'N'
      KeySchema:
        - AttributeName: id
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  
    
