AWSTemplateFormatVersion: 2010-09-09
Description: My API Gateway and Lambda function
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
      
      Path: /
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json
          import boto3   
          dynamodb = boto3.resource('dynamodb') 
          bookTable = dynamodb.Table('book')    
          def lambda_handler(event,context):
             bookTable.put_item(Item=event)
             return {
               'body': json.dumps('Added Entry Successfully!'),
               'statusCode': 200
               }
      Description: Example Lambda function
      FunctionName: t1
      Handler: index.lambda_handler
      MemorySize: 128
      Role: 
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Runtime: python3.8


